# These are supported funding model platforms

github: hezedu
open_collective: linux-remote
patreon: hezedu
# ko_fi: Replace with a single Ko-fi username
# tidelift: npm/linux-remote
custom: https://www.paypal.me/hezedu
