# These are supported funding model platforms

github: hezedu
patreon: hezedu
open_collective:  # linux-remote
ko_fi: # Replace with a single Ko-fi username
tidelift:  # npm/linux-remote
custom: # Replace with a single custom sponsorship URL
